name: "Check typescript types"
on:
    push:
jobs:
    check-types:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "21"
            - run: npm ci
            - run: tsc
